# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  	config.vm.provider "virtualbox" do |v|
		v.name = "client"
	end
	config.vm.box = "puphpet/debian75-x64"
	config.vm.hostname = "client"
	config.vm.provision :shell do |shell|
		shell.inline = "apt-get update;
					mkdir -p /etc/puppet/modules;
                  puppet module install puppetlabs/apache"
		end
	config.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "../manifests/"
		puppet.manifest_file = "client.pp"
	end
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "private_network", ip: "192.168.33.2"
    config.vm.synced_folder "../WebSessionProfiler_php", "/vagrant_data"
	config.vm.synced_folder "../configs/etc", "/vagrant_data/etc/"
end
